### ISSUE TITLE
False Positives 

### ISSUE THREAD

**Issue by etagwerker** [rubymem/bundler-leak#10]
Hey @bronzdoc, 

It seems that we have a problem with false positives. Some versions of some gems are known to be leaky, but it seems that `bundler-leak` is reporting them as leaky even if the project is using a patched version.

## Case 1 (reported in the `railsperf` Slack) 

"I just ran this against a project and I think I got two false-positives:"

```
zsh 2715  (git)-[paj/Introducing-bundler-leak]-% bundle leak
Name: redis
Version: 4.1.2
URL: https://github.com/redis/redis-rb/issues/612
Title: Memory Leak using Celluloid::Future
Solution: remove or disable this gem until a patch is available!

Name: sidekiq
Version: 5.2.7
URL: https://github.com/mperham/sidekiq/pull/2598
Title: Memory Leak in Sidekiq::Manager#real_thread
Solution: remove or disable this gem until a patch is available!

Vulnerabilities found!
```

"https://github.com/mperham/sidekiq/commit/d62ee8f9993512f26a405e7ac4431815b4230beb
&
https://github.com/redis/redis-rb/commit/d75708f6e05d9bba7dfec65880f9a55252f3fd2a
Seem to have addressed both of these leaks in earlier versions than we’re running."

## Case 2 (reported in the `railsperf` Slack) 

"The result on my project" 

```
ruby-mem-advisory-db: 9 advisories
Name: oj
Version: 3.6.4
URL: https://github.com/ohler55/oj/issues/229
Title: Memory Leak using Oj::Doc.open
Solution: remove or disable this gem until a patch is available!

Name: redis
Version: 4.0.2
URL: https://github.com/redis/redis-rb/issues/612
Title: Memory Leak using Celluloid::Future
Solution: remove or disable this gem until a patch is available!

Name: sidekiq
Version: 5.2.2
URL: https://github.com/mperham/sidekiq/pull/2598
Title: Memory Leak in Sidekiq::Manager#real_thread
Solution: remove or disable this gem until a patch is available!
```

**Comment by johnsyweb** [comment]
```sh
% bundle leak --version
bundler-leak 0.1.0 (advisories: 9)
```

Same deal:

```sh
% bundle leak
Name: redis
Version: 4.1.2
URL: https://github.com/redis/redis-rb/issues/612
Title: Memory Leak using Celluloid::Future
Solution: remove or disable this gem until a patch is available!

Name: sidekiq
Version: 5.2.7
URL: https://github.com/mperham/sidekiq/pull/2598
Title: Memory Leak in Sidekiq::Manager#real_thread
Solution: remove or disable this gem until a patch is available!

Vulnerabilities found!
```

**Comment by 23tux** [comment]
When just install it via `gem install bundler-leak` and directly run `bundle leak` afterwards, it still shows the false positives. So it doesn't work "out of the box", you still need a `bundle leak check --update` on your first run.

**Comment by etagwerker** [comment]
@23tux Thanks for your comment! I saw a similar comment in our blog, so I created https://github.com/rubymem/bundler-leak/issues/14 to keep track of that issue.
