### ISSUE TITLE
`bundle leak` doesn't work _out of the box_

### ISSUE THREAD

**Issue by etagwerker** [rubymem/bundler-leak#14]
Creating this issue to keep track of https://github.com/rubymem/bundler-leak/issues/10#issuecomment-527314668. 

It seems that `bundle leak check --update` is necessary for the tool to work _out of the box_

It would be great if `bundle leak` did an update the first time it runs. What do you think, @bronzdoc?

**Comment by jpanderson-outreach** [comment]
For what it's worth, I had a hard time getting `bundle leak check --update` to actually update as I'd pulled down before the new version. It looks like [the command to run is just being overwritten](https://github.com/rubymem/bundler-leak/blob/master/lib/bundler/plumber/database.rb#L102 the c):
```
              command = %w(git fetch --all)
              command = %w(git reset --hard origin/master)
              command << '--quiet' if options[:quiet]
```

So if you haven't fetched, it just resets hard to the same master you already have.

**Comment by bronzdoc** [comment]
Should be fixed in https://github.com/rubymem/bundler-leak/pull/25

Please let me know if not.
