### ISSUE TITLE
Add `--exit-on-error` option?

### ISSUE THREAD

**Issue by k1r8r0wn** [rubymem/bundler-leak#16]
Something like [`brakeman`'s](https://github.com/presidentbeef/brakeman/pull/991/files) gem feature?

**Comment by etagwerker** [comment]
@k1r8r0wn That sounds like a good idea. Do you want to take a stab at it?

**Comment by bronzdoc** [comment]
Giving this a closer look I don't see the benefit. 

bundler-leak doesn't track errors and people could create wrapper scripts around the `bundler-leak `api or client to achieve the same result of an `exit-on-error` option.

I'm going to close this but open to discuss it.
