### ISSUE TITLE
Ignore option

### ISSUE THREAD

**Issue by andyw8** [rubymem/bundler-leak#18]
It would be useful to have an `--ignore` option similar to what bundler-audit has.

**Comment by bronzdoc** [comment]
Hey @andyw8 thanks for the suggestion! could you elaborate how such option would work for bundler-leak? what would be a nice use case for a flag like that? thanks!

**Comment by andyw8** [comment]
Sure: I want to use this as part of a CI build. The legacy app I'm working on has some gems with known leaks. I do plan to fix upgrade those, but not immediately. I want to use bundler-leak to detect any *new* problems, and fail the build if any are found.

**Comment by bronzdoc** [comment]
@andyw8 cool.

What should we pass to the `--ignore` flag?

**Comment by andyw8** [comment]
How about `{gemname}-{issue number}`?

e.g. for https://github.com/rubymem/ruby-mem-advisory-db/blob/master/gems/celluloid/670.yml it would be `celluloid-670`.

**Comment by bronzdoc** [comment]
@andyw8 Sounds reasonable 👍
